packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/domain/*'
  - 'packages/application/*'
  - 'packages/infrastructure/*'

allowBuilds:
  '@google/genai': set this to true or false
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  simple-git-hooks: true
