import fs from 'fs';
import path from 'path';

const rootDir = process.cwd();
const tokensPath = path.join(rootDir, 'packages/design-tokens/tokens.json');
const motionPath = path.join(rootDir, 'packages/design-tokens/motion.json');
const typographyPath = path.join(rootDir, 'packages/design-tokens/typography.json');

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));
const motion = JSON.parse(fs.readFileSync(motionPath, 'utf8'));
const typography = JSON.parse(fs.readFileSync(typographyPath, 'utf8'));

// 1. Generate CSS Variables
let cssOutput = `/* Generated by build-tokens.ts - DO NOT EDIT DIRECTLY */\n:root {\n`;

// Colors
for (const [colorName, colorVal] of Object.entries(tokens.color)) {
  if (typeof colorVal === 'string') {
    cssOutput += `  --cds-color-${colorName}: ${colorVal};\n`;
  } else {
    for (const [shade, hex] of Object.entries(colorVal as Record<string, string>)) {
      cssOutput += `  --cds-color-${colorName}-${shade}: ${hex};\n`;
    }
  }
}

// Spacing
for (const [key, val] of Object.entries(tokens.spacing)) {
  cssOutput += `  --cds-space-${key}: ${val};\n`;
}

// Radius
for (const [key, val] of Object.entries(tokens.radius)) {
  cssOutput += `  --cds-radius-${key}: ${val};\n`;
}

// Motion
for (const [key, val] of Object.entries(motion.duration)) {
  cssOutput += `  --cds-motion-${key}: ${val};\n`;
}

cssOutput += `}\n`;

const cssDir = path.join(rootDir, 'packages/design-tokens/css');
if (!fs.existsSync(cssDir)) fs.mkdirSync(cssDir, { recursive: true });
fs.writeFileSync(path.join(cssDir, 'tokens.css'), cssOutput);

// 2. Generate TypeScript types and constants
const tsOutput = `/* Generated by build-tokens.ts - DO NOT EDIT DIRECTLY */
export const DESIGN_TOKENS = ${JSON.stringify(tokens, null, 2)} as const;
export const MOTION_TOKENS = ${JSON.stringify(motion, null, 2)} as const;
export const TYPOGRAPHY_TOKENS = ${JSON.stringify(typography, null, 2)} as const;
`;

const genDir = path.join(rootDir, 'packages/design-tokens/generated');
if (!fs.existsSync(genDir)) fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(path.join(genDir, 'tokens.ts'), tsOutput);

// 3. Generate Tailwind Theme Extension JS
const tailwindThemeOutput = `/* Generated by build-tokens.ts - DO NOT EDIT DIRECTLY */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.color, null, 2)},
      spacing: ${JSON.stringify(tokens.spacing, null, 2)},
      borderRadius: ${JSON.stringify(tokens.radius, null, 2)},
      boxShadow: ${JSON.stringify(tokens.shadow, null, 2)},
      zIndex: ${JSON.stringify(tokens.zIndex, null, 2)},
    },
  },
};
`;
fs.writeFileSync(path.join(genDir, 'tailwind-theme.js'), tailwindThemeOutput);

console.log(
  'Successfully generated tokens.css, generated/tokens.ts, and generated/tailwind-theme.js!'
);
